// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0hG0syxKlf0jnFAXjNvpw2khkkXdrhsk',
    appId: '1:525418813811:web:dcea9aeabfadea8eaa4d06',
    messagingSenderId: '525418813811',
    projectId: 'taxdriver-51edd',
    authDomain: 'taxdriver-51edd.firebaseapp.com',
    storageBucket: 'taxdriver-51edd.appspot.com',
    measurementId: 'G-SJXH1LXTNY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcPDwtoAxLQvL_3MDxGJy9QfhVlUh0K5o',
    appId: '1:525418813811:android:15928775532f971baa4d06',
    messagingSenderId: '525418813811',
    projectId: 'taxdriver-51edd',
    storageBucket: 'taxdriver-51edd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzWK4Ti6OXVWKJkjsk5AGrkG5m76a66mc',
    appId: '1:525418813811:ios:fce249ca7747999aaa4d06',
    messagingSenderId: '525418813811',
    projectId: 'taxdriver-51edd',
    storageBucket: 'taxdriver-51edd.appspot.com',
    iosClientId: '525418813811-3vf7neqrrpggcc0oouaumqp5bgtuc0ie.apps.googleusercontent.com',
    iosBundleId: 'com.example.wigootaxidriver',
  );
}
